version: '3.8'

services:
  app:
    build:
      context: .   # Context should point to the root of your project
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
